global:
  resolve_timeout: 5s

route:
  receiver: "webhook"
  group_wait: 1s
  group_interval: 5s
  repeat_interval: 1m

receivers:
  - name: "webhook"
    webhook_configs:
      - url: "http://localhost:5001/alert"
        send_resolved: true
